dfinity/oisy-wallet-signer

- package-lock.json
- package.json
We want to release a first version to npm.
> chore: release version v0.0.1

- README.md
The CI tests and checks have other names that those specified in the README.
> docs: correct img.shields badges urls

- README.md
The lib is a not a dev dependency.
> docs: typo in installation snippet

- README.md
- package-lock.json
- package.json
We want to release last improvement when local devepment happens on another port that the default.
> chore: next version

- .github/actions/prepare/action.yml
- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
> chore: node v22

- README.md
> chore: fmt

- README.md
Small redundancy in the README file.
> docs: remove redundancy

- README.md
`npm ci` is also required to run the demo.
> docs: npm ci for first usage of demo

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
Just a bit of maintance. Bump the dfinity libs in the lib and demo.
> build: bump dfinity libs

- src/services/signer.service.ts
For readability, particularly given that we will have to make changes in this area of the code base, I extracted a call to a dedicate private method.
- Extract code to method
No code changes hence no particular test changes.
> refactor: extract code for call consent message in service

- .github/dependabot.yml
> chore: format yml

- README.md
Update a note in the README following last improvements and addition of ICRC-2 approve and transfer from.
> docs: update client supported methods

- src/icrc-wallet.ts
I noticed that we did not had docs for the `IcrcWallet.approve`.
> docs: icrc approve

- demo/src/wallet_frontend/src/lib/ConsentMessage.svelte
- e2e/page-objects/party.page.ts
- e2e/page-objects/wallet.page.ts
We want to extend the E2E tests to validate the consent info level Ok or Warn.
> test: E2E consent message level

- package-lock.json
- package.json
We want to release #417.
- Bump library version for release
> chore: release version v0.1.1

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
Bump latest ic-js and version number for release.
> build: bump dependencies and version

- package-lock.json
- package.json
We want to release a version with the improvements regarding answering to read only requests (ready and supported standards).
- Bump version `v0.1.7`
> chore: bump for release version

- package-lock.json
- package.json
We released a new version of our eslint lib. We want to stay up-to-date here too.
> build: bump eslint

- package-lock.json
- package.json
Bump dev dependencies in lib to stay up-to-date.
Except TypeScript. This would still require some work #490.
> build: bump dev dependencies in lib

- demo/package-lock.json
- demo/package.json
> build: bump sveltekit in demo

- package-lock.json
- package.json
- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
- src/agent/custom-transform-agent.ts
- src/agent/http-agent-provider.spec.ts
- src/builders/signer.builders.spec.ts
- src/builders/signer.builders.ts
- src/constants/signer.builders.constants.ts
- src/icp-wallet.spec.ts
- src/icp-wallet.ts
- src/icrc-wallet.spec.ts
- src/icrc-wallet.ts
- src/mocks/call-utils.mocks.ts
- src/mocks/icrc-approve.mocks.ts
- src/mocks/icrc-transfer-from.mocks.ts
- src/mocks/icrc2-call-utils.mocks.ts
- src/relying-party.spec.ts
- src/relying-party.ts
- src/services/signer.service.ts
- src/services/signer.services.spec.ts
- src/sessions/signer.sessions.ts
- src/signer.spec.ts
- src/types/post-message.ts
- src/types/signer-builders.ts
- src/utils/call.assert.utils.ts
- src/utils/call.utils.ts
- src/utils/idl.utils.spec.ts
- src/utils/idl.utils.ts
Bumping `@dfinity/eslint-config-oisy-wallet` to latest version. Plus, I ran `eslint . --fix` to add the auto-fixes.
> build: bump eslint config library

- src/api/agent.api.spec.ts
There is a duplicated test for agent api.
> chore: remove duplicate test in agent api

- demo/package-lock.json
- demo/package.json
- demo/src/core/constants/app.constants.ts
- demo/src/relying_party_frontend/src/lib/components/GetICP.svelte
- demo/src/relying_party_frontend/src/routes/dev/+page.svelte
- demo/src/wallet_frontend/src/lib/ConfirmPermissions.svelte
- demo/src/wallet_frontend/src/lib/ConsentMessage.svelte
- demo/src/wallet_frontend/src/routes/+page.server.ts
- demo/vite.config.ts
- package-lock.json
- package.json
- src/agent/custom-transform-agent.spec.ts
Chore bump `@dfinity/eslint-config-oisy-wallet` in lib and demo.
> chore: bump eslint

- package-lock.json
- package.json
Stay up-to-date and close all bot PRs.
> build: bump lib dev dependencies

- demo/src/core/components/IconChevronDown.svelte
- demo/src/core/components/InputSelect.svelte
- demo/src/core/constants/app.constants.ts
- demo/src/relying_party_frontend/src/app.d.ts
- demo/src/relying_party_frontend/src/lib/components/Connect.svelte
- demo/src/relying_party_frontend/src/lib/components/ConnectAndRequestAccount.svelte
- demo/src/relying_party_frontend/src/lib/components/GetICP.svelte
- demo/src/relying_party_frontend/src/lib/components/SendICP.svelte
- demo/src/relying_party_frontend/src/lib/components/WalletUrl.svelte
- demo/src/relying_party_frontend/src/lib/stores/wallet.store.ts
- demo/src/relying_party_frontend/src/routes/+page.svelte
We also want to be able to test OISY staging with the demo.
- Add a store and a select for the OISY URL
> feat: customizable OISY url in the demo

- package-lock.json
- package.json
> chore: bump version v0.2.3 for release

- package-lock.json
- package.json
Since we are already here, maybe can release a small patch for #612.
- Bump next version in root package.json
> chore: prepare release v0.2.4

- demo/src/core/constants/app.constants.ts
- demo/src/relying_party_frontend/src/lib/components/WalletUrl.svelte
We want to be able to use www.fe1.oisy.com/sign as a wallet url in the demo app.
> feat: adds fe1 as wallet url

- demo/src/core/constants/app.constants.ts
- demo/src/relying_party_frontend/src/lib/components/WalletUrl.svelte
- Refactor code to not have a multiple similar constants
- Add `audit.oisy.com` to the list of test env
> feat: demo test domains plus add audit
