- package-lock.json
- package.json
The latest version of Internet Identity included in the Juno Docker image no longer requires a captcha for new user sign-ins. Therefore, to ensure the E2E test suite for this library succeeds with the updated Docker container, we need to bump the Playwright plugin, which has been updated accordingly.
> build: bump II playwright plugin for no captcha

- .eslintignore
- src/tsconfig.json
We aim to have separate `tsconfig` files: a main `tsconfig.json` for library rules, a `tsconfig.eslint.json` extending it for ESLint, and a `tsconfig.spec.json` for testing. While this setup works well with command-line tools, JetBrains IDE version 2024.2.x has issues resolving the test configuration. Consequently, the `vi` global type isn’t recognized, which causes the editor to display errors.
I reported this issue to JetBrains, who opened a tracking ticket: [https://youtrack.jetbrains.com/issue/WEB-69571](https://youtrack.jetbrains.com/issue/WEB-69571). It may be resolved eventually—or not.
In the meantime, a workaround is to add a `tsconfig.json` file in the `src` directory that extends the root `tsconfig.spec.json`.
> chore: workaround for Jetbrains IDE issue not resolving vi

- src/handlers/signer-success.handlers.spec.ts
- src/relying-party.spec.ts
- src/signer.spec.ts
- src/signer.ts
- src/types/signer-prompts.spec.ts
We've got constants for the permissions, so let's use them instead of duplicating their value.
> refactor: use ICRC-25 constants

- .github/workflows/lib-next.yml
The order of building the next was inverted in the action. As a result a next version cannot be published.
Example: https://github.com/dfinity/oisy-wallet-signer/actions/runs/11532355284
> build: fix ci next

- package-lock.json
- package.json
- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
We want to stay up-to-date so this PR bumps the dev dependencies.
Build needs Node v22 (types) provided in #321 to pass.
- Bump dependencies
- Adapt for breaking changes in Agent-js
> build: bump dev dependencies

- demo/package-lock.json
- demo/package.json
Bump recent dependencies in the demo (except eslint) and audit fix at the same time.
> build: bump demo dependencies and audit fix

- demo/package-lock.json
- demo/package.json
Vitest currently does not support vite v6, therefore not all dev dependencies related to Svelte in the demo can be upgraded.
- Update @sveltejs/kit svelte sass tailwindcss vitest in demo
> build: bump demo dev dependencies

- src/icrc-wallet.spec.ts
- src/mocks/icrc-call-utils.mocks.ts
We need valid arguments to develop tests for #360. Such arguments already exists, that's why this PR extract those mocks in a separate module.
> refactor: extract ICRC mocks

- src/icp-wallet.ts
- src/icrc-wallet.ts
- src/utils/call.utils.ts
- src/utils/idl.utils.spec.ts
- src/utils/idl.utils.ts
We want to reuse the IDL decoder utility for other features than only results, notably decoding args in  #360, that's why this PR renames the functions for a more generic purpose related to IDL.
No code changes functional wise.
No tests changes.
> refactor: rename IDL encoder and decoder utils

- package.json
- scripts/i18n.mjs
- src/i18n/en.json
- src/i18n/en.spec.ts
- src/types/i18n.ts
We have to generate texts in #360 and it annoys me to just hardcode english strings in the code, not really i18n friendly even though we are going to use english in a first version. So I implemented a similar approach as what we generally do in our apps with the twist that it generates zod types. This way we can just have a test that ensure that any new keys added to the json files is always reflected in the ts types.
> feat: i18n

- package-lock.json
- package.json
We released a new version of the ledger-icrc which contains a mapper for token metadata which we need in #360.
So this PR bumps the ic-js peer dependencies.
> build: bump ic-js peer to include token metadata mapper

- src/api/signer.api.spec.ts
- src/api/signer.api.ts
To generate custom Markdown for a consent message #360, we need the tokens' decimals and symbols. That's why we fetch this information through the ledger canister and add support for the `metadata` call to the `signer.api`.  
- The call will always be executed using an **update** call.  
- The `signer.api` is named as a layer rather than as a canister. From an architectural perspective, this is why we can add the call there.  
- In this library, we generally cache agents and actors for optimal performance. In this particular implementation, however, I skipped the overhead and added a TODO for it.  
- Add function that create an ICRC ledger from `@dfinity/ledger-icrc` and exposes `metadata`
> feat: integrate ledger metadata in the API

- src/builders/signer.builders.ts
- src/services/signer.service.ts
Follow-up of [review](https://github.com/dfinity/oisy-wallet-signer/pull/371#discussion_r1895823009). We add `TODO` for the future, to extend the lib to support i18n.
> chore: add TODO for support i18n

- src/services/signer.service.ts
We do not necesseraly need this but, since the main logic is actually already quite a long function and, the error contains some TODO, if felt like it would be a bit more readable to extract the error handling in a separate method.
> refactor: extract method notify error

- src/api/signer.api.spec.ts
- src/mocks/icrc-ledger.mocks.ts
We will reuse some metadata mocks in #360 therefore this PR extract the values into a dedicated module.
> refactor: extract ledger metadata mocks

- src/utils/format.utils.spec.ts
- src/utils/format.utils.ts
While developing an E2E tests I noticed that actually the ICP ledger enforce one minimal decimal. Therefore I think it makes sense to align the formatter to their implementation.
See `convert_tokens_to_string_representation` in https://github.com/dfinity/ic/blob/master/packages/icrc-ledger-types/src/icrc21/lib.rs#L577
- Set min decimals to one
> feat: format amount with min one decimal

- e2e/build-consent-message.spec.ts
- e2e/mocks/consent-message.mocks.ts
- e2e/page-objects/party.page.ts
- e2e/page-objects/wallet.page.ts
I don't really want to automate the test of the "Build consent message" in the CI because it would requires building the canister of #382 in the pipeline which would require some tooling and time but, it's still handy to have a test to run locally. That's why this PR add such an E2E test.
- New E2E test to assert the consent message that is generated from the library.
> e2e: skipped test for build consent message

- src/builders/signer.builders.ts
In #383, to implement ICRC2 approve builder, we will have to reuse few common patterns and code of the current ICRC1 transfer builder implementation. This PR refactor the code to make few functions reusable.
> refactor: extract common reusable code for builders

- src/utils/format.utils.spec.ts
- src/utils/format.utils.ts
In #383 we will need a date formatter as well. This implementation is not 100% similar as what's done in the ICP ledger but, it's close enought.
ICP ledger: `Thu, 06 May 2021 20:17:10 +0000`
This impl:  `Mon, Dec 30, 2024, 08:30:16 UTC`
> feat: format date utils

- src/builders/signer.builders.spec.ts
- src/mocks/icrc-approve.mocks.ts
We will need the new ICRC-2 approve mocks for #388 as well. That's why this PR extracts the mock from the builder spec file to a dedicated mocks module.
> refactor: extract ICRC-2 approve mocks

- src/icrc-wallet.ts
I noticed that the typescript type for the error interfaces were inverted in icrc-wallet.
> fix: transfer and approve error interfaces inverted

- src/icp-wallet.spec.ts
- src/icrc-wallet.spec.ts
- src/mocks/icrc2-call-utils.mocks.ts
We will reuse few of the mocks of ICRC2 approve for ICRC2 transfer from therefore it makes sense to rename variable and modules.
> refactor: rename icrc2 mock

- src/builders/signer.builders.spec.ts
- src/builders/signer.builders.ts
Similarly as for ICRC1 transfer, we should use the token default fee as fallback if no fee is provided in the ICRC2 approve because the fee are given by the ledger.
> fix: use token fee in approve builder

- src/builders/signer.builders.spec.ts
- src/builders/signer.builders.ts
- src/i18n/en.json
- src/types/i18n.ts
To avoid confusion, Prodsec suggest to avoid the use of the term "Subaccount" in the generated consent message of the library and always use the term "Account" even if the account contains a subaccount. This because the library does not trim the account but, always prints the textual representation defined by the ICRC standard.
- Remove labels "subaccount"
- Adapt builder and related tests
> feat: always display label "Account" in generate consent message

- src/builders/signer.builders.spec.ts
- src/builders/signer.builders.ts
- src/constants/signer.builders.constants.ts
ProdSec recommends asserting the size of arguments when building a consent message within the library, similar to how the ICP ledger does this, to prevent the Candid parser from crashing.
See https://github.com/dfinity/ic/blob/master/packages/icrc-ledger-types/src/icrc21/lib.rs#L426
- Implement assertion
- Refactor function `buildContentMessage` to pass down arguments for each builder
> feat: assert arg size when building consent message

- scripts/i18n.mjs
- src/types/blob.ts
- src/types/i18n.ts
- src/types/icrc-accounts.ts
- src/types/icrc-requests.ts
- src/types/icrc-responses.ts
- src/types/icrc-standards.ts
- src/types/post-message.ts
- src/types/principal.ts
- src/types/relying-party-options.ts
- src/types/relying-party-requests.ts
- src/types/relying-party.ts
- src/types/rpc.spec.ts
- src/types/rpc.ts
- src/types/signer-handlers.ts
- src/types/signer-options.ts
- src/types/signer-prompts.ts
- src/types/signer-sessions.ts
- src/types/signer.ts
- src/types/url.ts
Make Zod tree-shakable.
https://github.com/colinhacks/zod/issues/2596
Before:
```
import { z } from 'zod';
```
After:
```
import * as z from 'zod';
```
> feat: tree-shakable zod

- src/builders/signer.builders.spec.ts
- src/builders/signer.builders.ts
- src/utils/builders.utils.spec.ts
- src/utils/builders.utils.ts
Prodsec suggests displaying the decoded memo in the consent message built by the library as UTF-8 instead of hex, similar to what is done by the ICP ledger.
See: https://github.com/dfinity/ic/blob/master/packages/icrc-ledger-types/src/icrc21/lib.rs#L348
- Use `TextDecoder` to decode memo
- Create utils to decode the memo mostly for test purpose as it simplifies mocking `TextDecoder` without impacting other functions
> feat: build memo consent message utf-8

- package-lock.json
- package.json
In OISY often times we use the `next` version of `ic-js` packages. To avoid conflicts we normalize the versions to the major one.
> build: normalize @dfinity peer dependencies

- scripts/update-version.mjs
Similar to `ic-js` , we want to release the next version with no specific peer dependencies versions.
> build: make peer dependencies up-to-next when releasing next

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
- src/utils/call.utils.spec.ts
- src/utils/call.utils.ts
We recently set the agent-js dependencies to ^v2 which actually was a mistake as the library requires some improvements that were delivered in agent-js v2.1.x.
Since v2.1.3 is buggy and the agent-js has been patched in a new version, we revert to being explicit in terms of version requirements and bump to the latest version.
There is also an hidden / not communicated breaking changes in Agent-js v2.3.0. The `rootKey` has been modified from being always defined to being potentially `null`. That's why we have to adapt the code to catch potential exception.
We unfortunately have to bump and patch the change in the same PR because one necessit the other.
- Bump Agent-js v2.3.0 in library
- Add assertion and throw errors for `agent.rootKey` being potentially null
- Bump Agent-js v2.3.0 in demo
> feat: Agent-js v2.3.0 breaking change

- .github/dependabot.yml
We  reduce the frequency of dependabot PRs to monthly, since weekly leads to a bit too much maintenance for a lib that does not change that often.
> dependabot: reduce frequency

- package-lock.json
- package.json
For simplicity reason, downgrade TypeScript to avoid error such as following to popups when migrating to eslint v9:
```
Error: src/agent/agentjs-cbor-copy.ts(37,29): error TS2345: Argument of type 'Uint8Array<ArrayBufferLike>' is not assignable to parameter of type 'ArrayBuffer'.
Type 'Uint8Array<ArrayBufferLike>' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.
```
Ultimately we should solve those but, to ease the migration, it's easier to just stick to an older version of TypeScript as we do in OISY.
https://github.com/dfinity/oisy-wallet-signer/actions/runs/13391900122/job/37401311340?pr=474
> chore: downgrade typescript to v5.4.5

- README.md
Actually, any commands of the Juno CLI can be run using `npx`. So, we can simplify the README and remove the step about installing it.
Was:
```
npm i @junobuild/cli
juno dev start
```
Becomes:
```
npx juno dev start
```
> docs: simplify E2E tutorial by skipping the installation of the Juno CLI

- src/signer.spec.ts
Improvement to the tests for the hearbeat. Created for explanation purposes, will be merged in #478.
> test: Handle heartbeat messages even when the signer is busy

- src/signer.spec.ts
- src/signer.ts
When Kongswap sends the icrc29_status event while connecting, the Oisy wallet encounters a 'busy' error (SignerErrorCode.BUSY). This causes the Oisy Wallet Signer popup to close with a slight delay.
We are not exactly sure where the issue arises, but we assume that some changes in the clients (dapps or libraries) result in the relying party requesting the status while the signer is actually busy handling other requests. For example, this can occur if the client starts polling for status too frequently.
After some reflection, we also noticed that this potential issue could arise even if nothing had changed. Periodic status requests have been introduced to check whether the connection is still open and valid, and if not, to automatically disconnect the relying party—for instance, if the …
> feat: handle heartbeat messages even when the signer is busy

- src/signer.ts
All read-only message requests must be handled within a dedicated method (handleReadOnlyMessage). This enables the signer to specifically handle read-only methods to fulfil the requirement:
**Respond to message requests that don't require user approval while the signer is busy**
- Changed method name handleHeartbeatMessage(..) to handleReadOnlyMessage(..)
- Updated method code documentation
- Added TODO comment to handleReadOnlyMessage(..)
- 
No tests are affected by this change. I also did not find tests that would require a naming change, since no test directly called handleHeartbeatMessage(..)
> feat: Prepare the method to specifically handle readonly message requests 

- .github/workflows/pr-checks.yml
Similar to OISY, we want to ensure that PR titles follow conventional commit semantics and do not contain any links to Jira (which is not public).
The script is similar to the [one](https://github.com/dfinity/oisy-wallet/blob/main/.github/workflows/pr-checks.yml) of OISY minus the `(scope)`.
i.e.
OISY:
```
if [[ "$TITLE" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)(\([-a-zA-Z0-9,]+\))\!?\: ]]; then
```
Signer:
```
if [[ "$TITLE" =~ ^(feat|fix|chore|build|ci|docs|style|refactor|perf|test)\!?\: ]]; then
```
> chore: pr title and description checks

- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
The request payload is now transformed to include the nonce, ensuring it is correctly encoded and injected via a transform function.
All tests have been run successfully.
> feat: added new method addTransfrom to add nonce to icrc_49_call_canister call params

- src/api/signer.api.spec.ts
- src/api/signer.api.ts
- Updated the SignerApi.call method to accept an optional nonce property.
- Updated tests to cover both cases: with and without the nonce.
Added new unit test to cover new logic.
> feat: added nonce parameter to signer.api call method

- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
Added new nonceTransform to reassign nonce value if it is not provided by client.
Added new unit test to cover new logic.
> feat: added nonceTransform to reassign value for nonce

- package-lock.json
- package.json
E2E tests are currently failing on main and in PRs ([example](https://github.com/dfinity/oisy-wallet-signer/actions/runs/13840293026/job/38726882890?pr=505)). The issue is unrelated to our code but seems to be related to Playwright not properly awaiting element counts. While there is nothing mentioned in the CHANGELOG, it appears that bumping Playwright resolves the issue.
The test might also be flaky, but there haven't been any issues so far. That’s why I suggest first trying to bump Playwright.
- Bump latest Playwright
> test: fix playwright awaiting count elements

- demo/src/relying_party_frontend/src/lib/components/Accounts.svelte
- demo/src/relying_party_frontend/src/lib/components/PermissionsScopes.svelte
- demo/src/relying_party_frontend/src/lib/components/SupportedStandards.svelte
- demo/src/wallet_frontend/src/lib/ConfirmPermissions.svelte
The latest linter provided in [#516] is more strict about `each` and required each of those to be keyed.
For example:
```
30:6  error  Each block should have a key  svelte/require-each-key
```
- Add keys to each
> feat: add key for each in demo

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
Agent-js [v.2.4.0](https://github.com/dfinity/agent-js/releases/tag/v2.4.0) contains an improvement - supporting nonce for call - required to implement a feature in the signer. That's why we need to bump the library.
- Bum agent in lib and demo.
> build: bump agent-js v2.4.0

- .github/dependabot.yml
We want to remove the scope from the PR title (commit message) created by dependabot, so that `build(dev-deps):...` becomes `build:...`
According to [documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#commit-message--), to remove the `scope` in the PR title/commit message, we need to define the `prefix` value and not set the `include` parameter.
> ci: remove scope from PR message

- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
- src/mocks/custom-http-agent.mocks.ts
Integrated the new custom-transform-agent into CustomHttpAgent to enable transformation of icrc_49 calls.
Added tests to cover the logic by spying on the customTransform call.
> feat: integrated customTransfrom to customHttpAgent

- src/api/icrc21-canister.api.spec.ts
- src/api/icrc21-canister.api.ts
Added usage of defaultHttpAgent for icrc_21 call
Adjusted tests
> feat: added defaultAgent to icrc_21 call

- package-lock.json
- package.json
We want to release a version with the improvements for calling canisters using a nonce. 
- Bump version v0.1.8
> chore: bump for release version

- demo/package-lock.json
- demo/package.json
Resolve another Vite server vunerability ([GHSA-356w-63v5-8wf4](https://github.com/vitejs/vite/security/advisories/GHSA-356w-63v5-8wf4))
- Bump vite v6.2.6
> build: bump vite (GHSA-356w-63v5-8wf4)

- package-lock.json
- package.json
Utils [v.2.13.0](https://github.com/dfinity/ic-js/releases/tag/v69) contains an improvement - Added hashObject utility to generate a SHA-256 hash from the given object. To be used to generateHash.
Bump utils lib.
> build: bump dfinity-utils v.2.13.0

- demo/package-lock.json
- demo/package.json
Utils [v.2.13.0](https://github.com/dfinity/ic-js/releases/tag/v69) contains an improvement - Added hashObject utility to generate a SHA-256 hash from the given object. To be used to generateHash.
Bump utils demo.
> build: bump dfinity-utils v.2.13.0 demo

- src/agent/custom-transform-agent.ts
Replaced generateHash to hashObject to simplify the codebase and rely on a standardized, well-tested hashing implementation.
Replaced generateHash to hashObject.
> feat: replace generateHash with hashObject

- src/agent/custom-http-agent.spec.ts
- src/agent/custom-transform-agent.spec.ts
- src/agent/http-agent-provider.spec.ts
- src/api/icrc21-canister.api.spec.ts
- src/icp-wallet.spec.ts
- src/icrc-wallet.spec.ts
- src/utils/call.utils.spec.ts
With the update of the lint library in PR https://github.com/dfinity/oisy-wallet-signer/pull/554, there are some rules that require manual intervention.
In this specific case the rule `@typescript-eslint/consistent-type-imports` enforces that `import()` type annotations are forbidden.
> chore: apply lint rule `consistent-type-imports`

- src/builders/signer.builders.spec.ts
The test `'should throw error if arg is too long'` should throw error if arg is too long is already covered verbatim by the test right after:
```ts
it('should throw error if arg is too long', async () => {
await assertArgSize(buildContentMessageIcrc1Transfer);
});
```
> chore: Remove duplicate test in signer builder

- src/handlers/relying-party.handlers.spec.ts
- src/sessions/signer.sessions.spec.ts
- src/signer.spec.ts
- src/types/icrc-responses.spec.ts
With the update of the lint library in PR https://github.com/dfinity/oisy-wallet-signer/pull/554, there are some rules that require manual intervention.
In this specific case the rule `vitest/no-identical-title` enforces the usage of different titles for tests in the same context.
> chore: apply vitest lint rule `no-identical-title`

- src/builders/signer.builders.spec.ts
It does not change the effectiveness of the tests, but just for consistency, we add statement assertions to the expect statements in the test-suite for Signer builders.
> chore: add `expect` assertion for tests in Signer builders

- package-lock.json
- package.json
Juno Docker has been updated with latest version of Internet Identity to resolve an issue reported by a dev of the community regarding using the Playwright plugin with the latest version of II (https://github.com/dfinity/internet-identity-playwright/issues/56). For the same reason, we patched and released a new version of the plugin.
- Bump latest `@dfinity/internet-identity-playwright@2.0.0`
> chore: update @dfinity/internet-identity-playwright v2.0.0

- package-lock.json
- package.json
- src/agent/agentjs-cbor-copy.ts
- src/agent/custom-http-agent.spec.ts
- src/agent/custom-http-agent.ts
- src/builders/signer.builders.spec.ts
- src/mocks/custom-http-agent.mocks.ts
- src/services/signer.service.ts
- src/services/signer.services.spec.ts
- src/utils/agentjs-cbor-copy.utils.spec.ts
- src/utils/agentjs-cbor-copy.utils.ts
- src/utils/call.assert.utils.spec.ts
- src/utils/call.utils.ts
TypeScript [v5.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-7.html) ships a breaking changes regarding the `Uint8Array` and `ArrayBufferLike`. As a result, in addition to bumping TS, the code should be adapted as well.
- Bump latest TypeScript
- Use utility `uint8ToBuf` of `agent-js` for data handling. Which happens to be necessary in parts of the code where agent-js is overwritten as features are not built-in, so makes sense.
- Add few `@ts-ignore` exceptions because Agent-js currently except ArrayBuffer which are Uint8array or the contrary. I think this will be fixed in their next version, few types are already improved and the cbor encoder will change anyway - i.e. we'll also have to update the code.
> feat: migrate to TypeScript v5.8.3 and its breaking change Uint8Array<ArrayBufferLike>

- package-lock.json
- package.json
We need ic-js@next in OISY which contains a breaking change - not affecting the signer - in `ledger-icp` v3.
- Accept >= 2 version of ledger-icp
> build: accept ledger-icp v3

- demo/eslint.config.mjs
- demo/src/core/components/Balance.svelte
- demo/src/core/stores/alert.store.ts
- demo/src/core/stores/auth.store.ts
- demo/src/core/types/identity.ts
The demo incorrectly uses unknown `Option<...>` since we introduced the eslint rule library in #359.
- Remove usage of Option and disable rule
Example
> fix: demo Option types and disable eslint rule

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
- src/types/blob.ts
- src/types/hex-string.ts
- src/types/i18n.ts
- src/types/icrc-accounts.ts
- src/types/icrc-requests.ts
- src/types/icrc-responses.ts
- src/types/icrc-standards.ts
- src/types/post-message.ts
- src/types/relying-party-options.ts
- src/types/relying-party-requests.ts
- src/types/relying-party.ts
- src/types/rpc.spec.ts
- src/types/rpc.ts
- src/types/signer-handlers.ts
- src/types/signer-options.ts
- src/types/signer-prompts.ts
- src/types/signer-sessions.ts
- src/types/signer.ts
- src/utils/zod.utils.ts
Zod library v4 was officially released and we bumped it in `@dfinity/zod-schemas` in ic-js [release v71](https://github.com/dfinity/ic-js/releases/tag/v71). That's why, we upgrade also the library here.
- Bump zod-schemas and zod in the lib and demo
- Update juno config and plugin for the demo which also use above libs
- Adapt imports from `zod/v4` to `zod`
- Make the reference to zod and schemas in the lib a bit more open (e.g. ^4 insteadof ^4.0.0)
> build: bump zod v4

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
- src/types/blob.ts
- src/types/hex-string.ts
- src/types/i18n.ts
- src/types/icrc-accounts.ts
- src/types/icrc-requests.ts
- src/types/icrc-responses.ts
- src/types/icrc-standards.ts
- src/types/post-message.ts
- src/types/relying-party-options.ts
- src/types/relying-party-requests.ts
- src/types/relying-party.ts
- src/types/rpc.spec.ts
- src/types/rpc.ts
- src/types/signer-handlers.ts
- src/types/signer-options.ts
- src/types/signer-prompts.ts
- src/types/signer-sessions.ts
- src/types/signer.ts
- src/utils/zod.utils.ts
This PR revert the use of Zod v4 library We do so because we are unable to use the v4 release in OISY (see https://github.com/dfinity/oisy-wallet/issues/7788).
- Revert PR #607.
> feat: revert "build: bump zod v4 (#607)"

- package-lock.json
- package.json
A dev faced an issue today while trying to use the library ([forum](https://forum.dfinity.org/t/connecting-oisy-wallet-signer-uncaught-typeerror-void-0-is-not-a-function/53711)). I think this was due to the fact they used the zod-schemas v2 while the lib still requires v1. That's why I propose to pin to exactly v1.
- Set dependency to `1.0.0` instead of `^1.0.0`.
> build: pin zod-schemas to v1

- README.md
It's the second day in a row I do a bit of support for the signer. In both use cases, I think it would have been useful for the dev to debug locally but, it's not always clear how to run a signer locally. That's why I though about documenting how to run the pseudo wallet signer locally.
Requires #616
- Add how to run the demo wallet in the READM
> docs: "Running the Pseudo Wallet Signer Locally"

- package-lock.json
- package.json
This PR adds the new `@dfinity/cbor` library as a peer dependency. The migration to the new encoding and decoding will be implemented in #624 and #620.
- `npm i @dfinity/cbor --save-peer`
> build: add new cbor peer dependency

- package-lock.json
- package.json
There are actually no breaking changes per sé but, given the kind of changes we implemented - replacing the cbor library - I think it's worth to release it with a pseudo major/minor version.
- Bump next version `v0.3.0` for release.
I did some manual testing.
- New lib in relying party <> Old lib in OISY ✅
- New lib in relying party <> New lib in OISY ✅
- Old lib in relying party <> New lib in OISY ✅
- Identity kit demo <> New lib in OISY ✅
> chore: release version

- .github/actions/prepare/action.yml
There’s currently no clean way to install the unreleased dependencies required for #618 without using `--force` — it’s a pain. As a temporary workaround, we’ve configured the CI to use this flag.
⚠️ This PR must be reverted before publishing any new release.
- `--force` in CI prepare.
> build: temporary install deps with --force flag in ci

- src/utils/cbor.utils.spec.ts
While reviewing the "Expiry" topic I noticed that two tests were relying on `_value` internal proprety which has been deprecated. The tests were still passing because they compared "undefined ==== undefined".
- Replace inner value for test with function `toBigInt` exposed by object `Expiry`.
> test: fix expiry comparison

- demo/package-lock.json
- demo/package.json
- package-lock.json
- package.json
We want to release a version for AgentJS v3.
This PR integrates the compatible version of ic-js ([v73](https://github.com/dfinity/ic-js/releases/tag/v73) - not latest version `v74`, this will release separately), bumps AgentJS to latest (keep v3 as peer dependency in the lib) and set the version numbers for release.
- Bump ic-js v73 and agent-js (as described) in library
- Bump ic-js v73 and agent-js (as described) in demo
- Set version for lib release to `v0.4.0`
- Set version to `v0.4.0` in the demo - I'm thinking that we can start versioning the number in sync there as well.
> build: bump released ic-js and latest agent-js v3

- src/api/signer.api.ts
I spotted a type incorrectly import from the library `/dist/...` folder instead of from root.
- Update import to point to `@dfinity/ledger-icrc` and not `@dfinity/ledger-icrc/dist/...`
> fix: ledger-icrc import from root
